auth_server:
  # Public dummy UAA for local development usage only!
  # Username/password: credhub/password
  url: https://35.196.32.64:8443
  trust_store: src/test/resources/auth_server_trust_store.jks
  trust_store_password: changeit

encryption:
  provider: internal
  keys:
  - encryption_password: opensesame
    active: true
  - encryption_password: correcthorsebatterystaple
  key_creation_enabled: true
  
security:
  oauth2:
    resource:
      jwt:
        key_value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKRq5WybJla1u2xcZE1G
          ne5/y5R/gi4uZZwAcwooCQjvaLK1nBQQJSG3qDr/isgYbeoR59AaWbNV5SGGMAgb
          SWKaK24FlcQI03nSLnYoiEt10lnSEfUbHNoIoomR4s9BSbj+d4Q0cJa50zqc9I+e
          EwtQ6NjUiiBtTPhFVLjiDWTck6wzYqT5gEhydh7b6VuRUoBswwP8jpBvWLi6CTDB
          F9kvkDR+hGiIR0L6N1e8IMPa06Hmfz07eo9qKF9VQd2qEkwAX69e4wu0laLUqERT
          gYZcTzJc6z/xIEH5/aViK/+xVMaVlAWsw9hkaxJRu/C84R715/g0boZIJoqNT7jD
          8QIDAQAB
          -----END PUBLIC KEY-----
  authorization:
    acls:
      # Change to true to enable ACL enforcement
      enabled: false

logging:
  config: src/main/resources/log4j2.properties

server:
  port: 9000
  ssl:
    enabled: true
    key_store: src/test/resources/key_store.jks
    key_password: changeit
    key_alias: cert
    ciphers: ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    client_auth: want
    trust_store: src/test/resources/trust_store.jks
    trust_store_password: changeit
    trust_store_type: JKS
    enabled-protocols: TLSv1.2
