spring:
  datasource:
    username: admin
    password:
    url: jdbc:mariadb://localhost:3306/credhub_dev?usePipelineAuth=false&useBatchMultiSend=false
  flyway:
    locations: classpath:/db/migration/common,classpath:/db/migration/mysql
