spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    group:
      "dev": "dev-remote-uaa"

management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  server:
    ssl:
      enabled: false
    port: 9001
